# Generated by Django 5.1.2 on 2024-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField()),
                ('amenities', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='hall_images/')),
            ],
        ),
    ]
