# Generated by Django 5.1.3 on 2024-11-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='Untitled Event', max_length=255),
        ),
    ]
