# Generated by Django 5.1.3 on 2024-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0007_alter_hall_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='user',
        ),
        migrations.AddField(
            model_name='hall',
            name='user_name',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
