# Generated by Django 5.1.3 on 2024-11-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_remove_hall_user_name_hall_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
